server:
  port: 3002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # For development; later we use Flyway
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: my_jwt_secret_key
  refresh-secret: my_refresh_jwt_secret
  access-expiration: 900000       # 15 minutes
  refresh-expiration: 604800000   # 7 days

logging:
  level:
    root: INFO
