spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb+srv://abhiknayak:Abhik%401998@cluster0.8iiqxqw.mongodb.net/activity_service?retryWrites=true&w=majority
      database: activity_service
      # username: your_username   # uncomment if authentication is enabled
      # password: your_password   # uncomment if authentication is enabled
      # authentication-database: admin
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8082   # change port if needed