  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=micro_main
